import Head from "next/head.js";

export default function Home({ name }) {
    return (
        <>
            <Head>
                <title>Home Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container">
                <p>HomePage: {name} </p>
            </main>
        </>
    );
}

export async function getServerSideProps() {
    return {
        props: { name: "LARBI Ishak" },
    };
}
